{{- if .Values.gatewayApi.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oss-ai-agent-tool.gatewayServiceAccountName" . }}
  labels:
    {{- include "oss-ai-agent-tool.labels" . | nindent 4 }}
  {{- with .Values.gatewayApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

