{{- if and .Values.indexer.enabled .Values.indexer.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oss-ai-agent-tool.indexerServiceAccountName" . }}
  labels:
    {{- include "oss-ai-agent-tool.labels" . | nindent 4 }}
  {{- with .Values.indexer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

