global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'orchestrator'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['orchestrator:4000']
  - job_name: 'gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['gateway:8080']
  - job_name: 'indexer'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['indexer:7071']

