# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Kubesec

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '31 14 * * 3'

jobs:
  lint:
    name: Kubesec
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        manifest:
          - charts/oss-ai-agent-tool/templates/gateway-deployment.yaml
          - charts/oss-ai-agent-tool/templates/gateway-service.yaml
          - charts/oss-ai-agent-tool/templates/indexer-deployment.yaml
          - charts/oss-ai-agent-tool/templates/indexer-service.yaml
          - charts/oss-ai-agent-tool/templates/ingress.yaml
          - charts/oss-ai-agent-tool/templates/jaeger.yaml
          - charts/oss-ai-agent-tool/templates/kafka.yaml
          - charts/oss-ai-agent-tool/templates/langfuse.yaml
          - charts/oss-ai-agent-tool/templates/networkpolicy.yaml
          - charts/oss-ai-agent-tool/templates/orchestrator-deployment.yaml
          - charts/oss-ai-agent-tool/templates/orchestrator-hpa.yaml
          - charts/oss-ai-agent-tool/templates/orchestrator-service.yaml
          - charts/oss-ai-agent-tool/templates/postgres.yaml
          - charts/oss-ai-agent-tool/templates/rabbitmq.yaml
          - charts/oss-ai-agent-tool/templates/redis.yaml
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run kubesec scanner
        uses: controlplaneio/kubesec-action@43d0ddff5ffee89a6bb9f29b64cd865411137b14
        with:
          input: ${{ matrix.manifest }}
          format: template
          template: template/sarif.tpl
          output: kubesec-results-${{ replace(matrix.manifest, '/', '-') }}.sarif
          exit-code: "0"

      - name: Upload Kubesec scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: kubesec-results-${{ replace(matrix.manifest, '/', '-') }}.sarif
